(* From RSL Require Import Prelude. *)

(* From stdpp Require Import gmap. *)

(* From Ltac2 Require Import Ltac2 Printf. *)

(* From RSL Require Import RelLogic.Def. *)

(* Local Lemma update_get_reg : ∀ ρ1 ρ2 r1 r2 v1 v2, *)
(*   ρ2 = set_reg r1 v1 ρ1 -> *)
(*   r1 <> r2 -> *)
(*   get_reg r2 ρ1 = v2 -> *)
(*   get_reg r2 ρ2 = v2. *)
(* Proof using Type. *)
(*   intros ρ1 ρ2 r1 r2 v1 v2 H Hneq Hreg. *)
(*   unfold get_reg, set_reg in *. subst. *)
(*   now rewrite (lookup_insert_ne ρ1). *)
(* Qed. *)

(* Local Lemma update_set_reg : ∀ ρ1 ρ2 r v, *)
(*   ρ2 = set_reg r v ρ1 -> *)
(*   get_reg r ρ2 = v. *)
(* Proof using Type. *)
(*   intros ρ1 ρ2 r v H. *)
(*   unfold get_reg, set_reg in *. *)
(*   subst. now rewrite (lookup_insert_eq ρ1). *)
(* Qed. *)

(* Ltac2 check (b: bool) : unit := *)
(*   match b with *)
(*   | true => () *)
(*   | false => Control.zero (Tactic_failure (Some (fprintf "Check failed"))) *)
(*   end. *)

(* Ltac2 rec update_regmap_loop (h: ident) (old_map: constr) (tac: unit -> unit) *)
(*   : unit := *)
(*   match! goal with *)
(*   | [ hr : get_reg _ ?m = _ |- _ ] => *)
(*       check (Constr.equal m old_map); *)
(*       let hc := Control.hyp h in *)
(*       apply (update_get_reg $old_map _ _ _ _ _ $hc) in $hr; *)
(*       Control.dispatch [ *)
(*           (fun () => *)
(*              printf "Renamed %t in %I" m hr; *)
(*              update_regmap_loop h old_map tac); *)
(*           tac *)
(*         ] *)
(*   | [ |- _ ] => () *)
(*   end. *)

(* Ltac2 update_regmap (h: ident) (old_map: constr) (tac: unit -> unit) *)
(*   : unit := *)
(*   update_regmap_loop h old_map tac. *)
(* (* ; *) *)
(* (*   apply update_set_reg in $h *) *)

(* Ltac2 do_reg_update (reg: constr) (val: constr) (old: ident) (tac: unit -> unit) := *)
(*   let rold := Fresh.in_goal @old in *)
(*   let rnew := Fresh.in_goal @new in *)
(*   let hreg := Fresh.in_goal @Hreg in *)
(*   Std.rename [(old, rold)]; *)
(*   let rold_c := Control.hyp rold in *)
(*   remember (set_reg $reg $val $rold_c) as $rnew eqn:$hreg; *)
(*   update_regmap hreg rold_c tac. *)
(*   (* Control.focus 1 1 (fun () => *) *)
(*   (*                      (* Std.clear [rold]; *) *) *)
(*   (*                      Std.rename [(rnew, old)]). *) *)

(* Ltac2 print_goal () := *)
(*   let g := Control.goal () in *)
(*   Message.print (Message.of_constr g). *)

(* Ltac2 iRegUpdate (tac: unit -> unit) : unit := *)
(*   Std.hnf { Std.on_hyps := Some [] ; Std.on_concl := Std.AllOccurrences }; *)
(*   lazy_match! goal with *)
(*   | [ |- logic_set_s_reg ?r ?v _ _ (?s, _) ] => *)
(*       printf "We have %t %t and %t" r v s *)
(*       (* do_reg_update r v () tac *) *)
(*   end. *)

(* Goal *)
(*   ∀ x m r1 r2 r3 ρ, *)
(*   r1 <> r2 -> *)
(*   r1 <> r3 -> *)
(*   get_reg r2 ρ = 0%Z -> *)
(*   get_reg r3 ρ = 1000%Z -> *)
(*   logic_set_s_reg r1 (1%Z) (fun _ _ => True) x (ρ, m). *)
(*   intros. *)
(*   iRegUpdate (fun () => printf "Hey !"). *)
  
(*   simpl in Hrmap. *)
(*   (* do_reg_update 'r1 '(1%Z) @ρ (fun () => printf "Hey !"). *) *)


(* (* Ltac update_regmap H old tac := *) *)
(* (*   repeat match goal with *) *)
(* (*     | [ Hr: get_reg _ old = _ |- _ ] => *) *)
(* (*         apply (update_get_reg _ _ _ _ _ _ H) in Hr; *) *)
(* (*         [|tac; done] *) *)
(* (*     end; *) *)
(* (*   apply update_set_reg in H. *) *)

(* (* Ltac set_reg_update r v old tac := *) *)
(* (*   let rold := fresh "old" in *) *)
(* (*   let rnew := fresh "new" in *) *)
(* (*   let Hreg := fresh "Hreg" in *) *)
(* (*   rename old into rold; *) *)
(* (*   remember (set_reg r v rold) as rnew eqn:Hreg; *) *)
(* (*   update_regmap Hreg rold tac; *) *)
(* (*   clear rold; *) *)
(* (*   rename rnew into old. *) *)

(* (* Ltac iRegUpdate := *) *)
(* (*   match goal with *) *)
(* (*   | |- logic_set_s_reg ?r ?v _ _ (?old, _) => *) *)
(* (*       unfold logic_set_s_reg; simpl; *) *)
(* (*       set_reg_update r v old lia *) *)
(* (*   | |- logic_set_t_reg ?r ?v _ (?old, _) _ => *) *)
(* (*       unfold logic_set_s_reg; simpl; *) *)
(* (*       set_reg_update r v old lia *) *)
(* (*   end. *) *)
